image: jessie-node10-ansible:latest

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build:assets:staging
    - npm run build:server:staging
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - export PROJECT_NAME=`echo $CI_PROJECT_NAME | awk -F'-' 'sub(FS $NF,x)'`
    - ansible-playbook ./deploy.yml -i $PROJECT_NAME-direct.snpdev.ru, --extra-vars="project=$PROJECT_NAME" --extra-vars="build_type=ssr"
  only:
    - testing
